// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateProductV1ProductNodesPostData, CreateProductV1ProductNodesPostErrors, CreateProductV1ProductNodesPostResponses, CreateProductV1ProductsPostData, CreateProductV1ProductsPostErrors, CreateProductV1ProductsPostResponses, CreateSaleV1SalesPostData, CreateSaleV1SalesPostErrors, CreateSaleV1SalesPostResponses, CreateUserV1WebhooksClerkUsersPostData, CreateUserV1WebhooksClerkUsersPostResponses, DeleteProductsV1ProductsObjIdDeleteData, DeleteProductsV1ProductsObjIdDeleteErrors, DeleteProductsV1ProductsObjIdDeleteResponses, DeleteProductV1ProductNodesObjIdDeleteData, DeleteProductV1ProductNodesObjIdDeleteErrors, DeleteProductV1ProductNodesObjIdDeleteResponses, HealthHealthGetData, HealthHealthGetResponses, ListNodesTreeV1ProductNodesTreeGetData, ListNodesTreeV1ProductNodesTreeGetResponses, ListNodesV1ProductNodesGetData, ListNodesV1ProductNodesGetResponses, ListProductsV1ProductsGetData, ListProductsV1ProductsGetResponses, ListSalesV1SalesGetData, ListSalesV1SalesGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Products
 */
export const listProductsV1ProductsGet = <ThrowOnError extends boolean = false>(options?: Options<ListProductsV1ProductsGetData, ThrowOnError>) => (options?.client ?? client).get<ListProductsV1ProductsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/v1/products/',
    ...options
});

/**
 * Create Product
 */
export const createProductV1ProductsPost = <ThrowOnError extends boolean = false>(options: Options<CreateProductV1ProductsPostData, ThrowOnError>) => (options.client ?? client).post<CreateProductV1ProductsPostResponses, CreateProductV1ProductsPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/products/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Products
 */
export const deleteProductsV1ProductsObjIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProductsV1ProductsObjIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProductsV1ProductsObjIdDeleteResponses, DeleteProductsV1ProductsObjIdDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/products/{obj_id}',
    ...options
});

/**
 * List Nodes
 */
export const listNodesV1ProductNodesGet = <ThrowOnError extends boolean = false>(options?: Options<ListNodesV1ProductNodesGetData, ThrowOnError>) => (options?.client ?? client).get<ListNodesV1ProductNodesGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/v1/product_nodes/',
    ...options
});

/**
 * Create Product
 */
export const createProductV1ProductNodesPost = <ThrowOnError extends boolean = false>(options: Options<CreateProductV1ProductNodesPostData, ThrowOnError>) => (options.client ?? client).post<CreateProductV1ProductNodesPostResponses, CreateProductV1ProductNodesPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/product_nodes/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List Nodes Tree
 */
export const listNodesTreeV1ProductNodesTreeGet = <ThrowOnError extends boolean = false>(options?: Options<ListNodesTreeV1ProductNodesTreeGetData, ThrowOnError>) => (options?.client ?? client).get<ListNodesTreeV1ProductNodesTreeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/v1/product_nodes/tree',
    ...options
});

/**
 * Delete Product
 */
export const deleteProductV1ProductNodesObjIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProductV1ProductNodesObjIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProductV1ProductNodesObjIdDeleteResponses, DeleteProductV1ProductNodesObjIdDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/product_nodes/{obj_id}',
    ...options
});

/**
 * List Sales
 */
export const listSalesV1SalesGet = <ThrowOnError extends boolean = false>(options?: Options<ListSalesV1SalesGetData, ThrowOnError>) => (options?.client ?? client).get<ListSalesV1SalesGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/v1/sales/',
    ...options
});

/**
 * Create Sale
 */
export const createSaleV1SalesPost = <ThrowOnError extends boolean = false>(options: Options<CreateSaleV1SalesPostData, ThrowOnError>) => (options.client ?? client).post<CreateSaleV1SalesPostResponses, CreateSaleV1SalesPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/v1/sales/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create User
 */
export const createUserV1WebhooksClerkUsersPost = <ThrowOnError extends boolean = false>(options?: Options<CreateUserV1WebhooksClerkUsersPostData, ThrowOnError>) => (options?.client ?? client).post<CreateUserV1WebhooksClerkUsersPostResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/v1/webhooks/clerk/users/',
    ...options
});

/**
 * Health
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) => (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/health',
    ...options
});
