// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ProductCreateDTO
 */
export type ProductCreateDto = {
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Buy Price
     */
    buy_price: number | string;
    /**
     * Sell Price
     */
    sell_price: number | string;
    /**
     * Quantity
     */
    quantity: number;
};

/**
 * ProductNodeCreateDTO
 */
export type ProductNodeCreateDto = {
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
};

/**
 * ProductNodeReadDTO
 */
export type ProductNodeReadDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id?: number | null;
    /**
     * Children
     */
    children?: Array<number>;
    /**
     * Products
     */
    products?: Array<number>;
};

/**
 * ProductNodeTreeDTO
 */
export type ProductNodeTreeDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Children
     */
    children?: Array<ProductNodeTreeDto>;
    /**
     * Products
     */
    products?: Array<ProductReadTreeDto>;
};

/**
 * ProductReadDTO
 */
export type ProductReadDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Node Id
     */
    node_id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Buy Price
     */
    buy_price: string;
    /**
     * Sell Price
     */
    sell_price: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ProductReadTreeDTO
 */
export type ProductReadTreeDto = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Buy Price
     */
    buy_price: string;
    /**
     * Sell Price
     */
    sell_price: string;
    /**
     * Quantity
     */
    quantity: number;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type ListProductsV1ProductsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/products/';
};

export type ListProductsV1ProductsGetResponses = {
    /**
     * Response List Products V1 Products  Get
     *
     * Successful Response
     */
    200: Array<ProductReadDto>;
};

export type ListProductsV1ProductsGetResponse = ListProductsV1ProductsGetResponses[keyof ListProductsV1ProductsGetResponses];

export type CreateProductV1ProductsPostData = {
    body: ProductCreateDto;
    path?: never;
    query?: never;
    url: '/v1/products/';
};

export type CreateProductV1ProductsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProductV1ProductsPostError = CreateProductV1ProductsPostErrors[keyof CreateProductV1ProductsPostErrors];

export type CreateProductV1ProductsPostResponses = {
    /**
     * Successful Response
     */
    200: ProductReadDto;
};

export type CreateProductV1ProductsPostResponse = CreateProductV1ProductsPostResponses[keyof CreateProductV1ProductsPostResponses];

export type DeleteProductsV1ProductsObjIdDeleteData = {
    body?: never;
    path: {
        /**
         * Obj Id
         */
        obj_id: number;
    };
    query?: never;
    url: '/v1/products/{obj_id}';
};

export type DeleteProductsV1ProductsObjIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProductsV1ProductsObjIdDeleteError = DeleteProductsV1ProductsObjIdDeleteErrors[keyof DeleteProductsV1ProductsObjIdDeleteErrors];

export type DeleteProductsV1ProductsObjIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListNodesV1ProductNodesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/product_nodes/';
};

export type ListNodesV1ProductNodesGetResponses = {
    /**
     * Response List Nodes V1 Product Nodes  Get
     *
     * Successful Response
     */
    200: Array<ProductNodeReadDto>;
};

export type ListNodesV1ProductNodesGetResponse = ListNodesV1ProductNodesGetResponses[keyof ListNodesV1ProductNodesGetResponses];

export type CreateProductV1ProductNodesPostData = {
    body: ProductNodeCreateDto;
    path?: never;
    query?: never;
    url: '/v1/product_nodes/';
};

export type CreateProductV1ProductNodesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProductV1ProductNodesPostError = CreateProductV1ProductNodesPostErrors[keyof CreateProductV1ProductNodesPostErrors];

export type CreateProductV1ProductNodesPostResponses = {
    /**
     * Successful Response
     */
    200: ProductNodeReadDto;
};

export type CreateProductV1ProductNodesPostResponse = CreateProductV1ProductNodesPostResponses[keyof CreateProductV1ProductNodesPostResponses];

export type ListNodesTreeV1ProductNodesTreeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/product_nodes/tree';
};

export type ListNodesTreeV1ProductNodesTreeGetResponses = {
    /**
     * Response List Nodes Tree V1 Product Nodes Tree Get
     *
     * Successful Response
     */
    200: Array<ProductNodeTreeDto>;
};

export type ListNodesTreeV1ProductNodesTreeGetResponse = ListNodesTreeV1ProductNodesTreeGetResponses[keyof ListNodesTreeV1ProductNodesTreeGetResponses];

export type DeleteProductV1ProductNodesObjIdDeleteData = {
    body?: never;
    path: {
        /**
         * Obj Id
         */
        obj_id: number;
    };
    query?: never;
    url: '/v1/product_nodes/{obj_id}';
};

export type DeleteProductV1ProductNodesObjIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProductV1ProductNodesObjIdDeleteError = DeleteProductV1ProductNodesObjIdDeleteErrors[keyof DeleteProductV1ProductNodesObjIdDeleteErrors];

export type DeleteProductV1ProductNodesObjIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
